### ISSUE TITLE
:Autolinkbuffer not existend, gz-mapping not there

### ISSUE THREAD

**Issue by Garonenur** [tomtom/autolinker_vim#1]
Hi,
I tried to use this plugin for todo.txt files, as the notes added to tasks there are linked with `file://`.

I checked with `git grep`, because `:Autolinkbuffer` was unknown to vim, and the only appearance of that command is in documentation files, but nowhere else?
Also, the mappings for autolinker are unknown to vim, even though `g:autolinker#nmap` is set to `gz`
Do you need any more information?

**Comment by Garonenur** [comment]
okay, I dug around a little in the code and found the command `:Albuffer` which does the trick to activate autolinker for a buffer - but the auto detection for todo.txt-files does not work for now. (I could work around this by calling `:Albuffer` in `after/ftplugin/ttodo.vim`, or adding that filetype to the list).

**Comment by tomtom** [comment]
If the autolink plugin is loaded, Autolink should be automatically be enabled forbuffers with filetype ttodo. You might want to check the output of `:autocmd AutoLinker BufWinEnter` and `:echo g:autolinker_filetypes` if this actually is the case.

**Comment by Garonenur** [comment]
this seems right:
`g:autolinker_filetypes ['text', 'txt', 'todo', 'ttodo', 'todotxt', 'md', 'markdown', 'markdown.pandoc', 'tex', 'latex']`
but `autocmd AutoLinker BufWinEnter` gives:
`E216: No such group or event: AutoLinker BufWinEnter`

**Comment by Garonenur** [comment]
as always: thanks for the fast response and fix!
It seems to work, but I get an error message:

```
Error detected while processing function autolinker#EnableBuffer..tlib#list#Uniq:
line   12:
E713: Cannot use empty key for Dictionary
E713: Cannot use empty key for Dictionary
```

is this related to the fix?

**Comment by tomtom** [comment]
> is this related to the fix? 

Please update tlib.

**Comment by Garonenur** [comment]
ah. should always update that one with the others. thanks again.
I really should get to learn more vimscript, so I can send you fixes instead of issues ;)
