### ISSUE TITLE
How to configure hypertext links?

### ISSUE THREAD

**Issue by sdothum** [tomtom/autolinker_vim#2]
Glancing around, I am assuming autolinker can perform hypertext links similar to viki and vimwiki for text structures

[[ link ]] 
[[ link | text ]]

where link may contain more than one word. I am hoping to use autolinker to replace vimwiki (as I don't need all of its functionality and plethora of keymappings) and prefer to use other markup plugins for highlighting. So.. how can one configure autolinker to provide hypertext links with markup documents (assuming it can)?

**Comment by tomtom** [comment]
> [[ link ]]
> [[ link | text ]]
>
> where link may contain more than one word.

That is, "link" could contain whitespace?

**Comment by tomtom** [comment]
> [[ link ]]
> [[ link | text ]]

We'd need a filetype to make this work.

**Comment by sdothum** [comment]
Yes, the link may contain blanks i.e. multiple words between the square brackets. My documents containing such hypertext link structures are given filetype markdown.

**Comment by tomtom** [comment]
> My documents containing such hypertext link structures are
> given filetype markdown.

That's not standard markdown syntax though, is it?

**Comment by sdothum** [comment]
No, it"s not. I have just been playing around with my existing vimwiki folders and seeting if there was a lighter way to manage the hypertext documents -- I really only used the hypertext feature of vimwiki for the most part. 

Viki in minor mode seems to work well -- though, doesn't work with the second vimwiki link form [[ link | text ]]. I thought autolinker might be lighter plugin if it could be configured appropriately to handle both these link structures.
